- name: Python
  logo: Python
  url: https://www.python.org/
  color: '#3776AB'
  projects:
    - url: https://github.com/Om-Kulkarni/Distributed-Multi-Camera-Segmentation-Pipeline
    - url: https://github.com/Om-Kulkarni/Realtime-SegDepth-Pipeline
    - url: https://github.com/Om-Kulkarni/Tiago-VR-Teleoperation
    - url: https://github.com/Om-Kulkarni/NAO-HRI-Emotional-Study

- name: C++
  logo: C++
  url: https://isocpp.org/
  color: '#00599C'
  projects:
    # Professional work[cite: 19, 21]. Add any public C++ repos here.

- name: ROS (Robotic Operating System)
  logo: ROS
  url: https://www.ros.org/
  color: '#22314E'
  projects:
    - url: https://github.com/Om-Kulkarni/Franka-ROS-Docker-Setup
    - url: https://github.com/Om-Kulkarni/Tiago-VR-Teleoperation

- name: PyTorch
  logo: PyTorch
  url: https://pytorch.org/
  color: '#EE4C2C'
  projects:
    - url: https://github.com/Om-Kulkarni/Distributed-Multi-Camera-Segmentation-Pipeline
    - url: https://github.com/Om-Kulkarni/Realtime-SegDepth-Pipeline
    - url: https://github.com/Om-Kulkarni/Material-Sorting-Foundation-Models

- name: Docker
  logo: Docker
  url: https://www.docker.com/
  color: '#2496ED'
  projects:
    - url: https://github.com/Om-Kulkarni/Franka-ROS-Docker-Setup

- name: Unity
  logo: Unity
  url: https://unity.com/
  color: '#000000'
  projects:
    - url: https://github.com/Om-Kulkarni/Tiago-VR-Teleoperation
    - url: https://github.com/Om-Kulkarni/VR-Teleoperation-Eye-Tracking-Dissertation

- name: MATLAB
  logo: MATLAB
  url: https://www.mathworks.com/products/matlab.html
  color: '#0076A8'
  projects:
    - url: https://github.com/Om-Kulkarni/Computed-Torque-Control-Manipulator

- name: Ray Framework
  logo: Ray
  url: https://www.ray.io/
  color: '#0070E0'
  projects:
    - url: https://github.com/Om-Kulkarni/Distributed-Multi-Camera-Segmentation-Pipeline