name: stack

on:
  push:
    branches:
      - main
    paths:
      - 'stack.yml' # Only run when stack.yml is changed
  workflow_dispatch: # Allow manual runs

jobs:
  profile_stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gleich/profile_stack@master